// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma 7+ moved datasource URLs out of schema.prisma
    // - DATABASE_URL: pooling (PgBouncer) for runtime client adapter
    // - DIRECT_URL: direct connection for migrations
    // Prisma Migrate should use a direct connection (not PgBouncer).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
    directUrl: process.env["DIRECT_URL"],
  },
});
